### ISSUE TITLE
spi mode is busted

### ISSUE THREAD

**Issue by HollisTech** [adafruit/Adafruit_BMP280_Library#28]

**Comment by HollisTech** [comment]
line 46 AdaFruit_BMP280.cpp: 
 *_spi = *theSPI;
should be:
 _spi = theSPI;

As is, this will crash in Adafruit_BMP280 ctor for spi mode. The code should be copying a pointer, not the object.

**Comment by ladyada** [comment]
@hoffmannjan please look and fix ASAP

**Comment by ladyada** [comment]
please try the latest commit
