### ISSUE TITLE
comment should be 0.5 ms 

### ISSUE THREAD

**Issue by hayden-t** [adafruit/Adafruit_BMP280_Library#30]
https://github.com/adafruit/Adafruit_BMP280_Library/blob/73636da7e89783d66649dbd9448a508c4a1e2f25/Adafruit_BMP280.h#L141

![image](https://user-images.githubusercontent.com/1000743/62420406-fb7b6200-b6d4-11e9-8c4e-20b83eca7c4c.png)

same goes for 001 = 62.5

**Comment by ladyada** [comment]
ooh, can you submit a PR to fix :)
