### ISSUE TITLE
Upgraded library to v 1.0.5 has wrong address

### ISSUE THREAD

**Issue by thearduinoguy** [adafruit/Adafruit_BMP280_Library#34]
The I2C address from library version 1.0.4 to 1.0.5 ha changed the address from 0x76 to 0x77 and broken it. Address needs to be 0x76 for it to work.

**Comment by ladyada** [comment]
hiya address has always been 0x77 ?
https://github.com/adafruit/Adafruit_BMP280_Library/blob/master/Adafruit_BMP280.h#L31

https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/i2c-sensors-and-devices#wiring-5-10

**Comment by ladyada** [comment]
closed due to lack of response
