### ISSUE TITLE
Pa or hPa?

### ISSUE THREAD

**Issue by bleckers** [adafruit/Adafruit_BMP280_Library#35]
In the library cpp file, the code states:

```
/*!
 * Reads the barometric pressure from the device.
 * @return Barometric pressure in hPa.
 */
float Adafruit_BMP280::readPressure() {
```

However in the example it states:

```
    Serial.print(F("Pressure = "));
    Serial.print(bmp.readPressure());
    Serial.println(" Pa");
```

Are these libraries returning Pa or hPa?

**Comment by bleckers** [comment]
Getting values of 101631.3 leads me to believe this library returns Pa, unless we are on Venus or something?

**Comment by ladyada** [comment]
yes it returns Pa, if you submit a PR for the doc fix, we'll merge!

**Comment by bleckers** [comment]
Done! Thank you :D

**Comment by ladyada** [comment]
you have to PR it next

**Comment by kevinjwalters** [comment]
This is _inconsistent_ with the specification/guidelines on https://learn.adafruit.com/using-the-adafruit-unified-sensor-driver/how-does-it-work#standardised-si-units-for-sensor-data-2-2 which states hPa (hecto-Pascals). I noticed this on the video for CLUE: https://www.youtube.com/watch?v=Nz38vF2W8BI&t=11s (look closely at values on y axis)

**Comment by ladyada** [comment]
readPressure() is Pa, but the Unified sensor example (sensortest) is in hPa
