### ISSUE TITLE
Will this work on a Beaglebone Black?

### ISSUE THREAD

**Issue by mikelupo** [adafruit/Adafruit_BMP280_Library#4]
Having issues getting the sketch to compile for the BB on the Cloud 9 IDE. It says it can't find the library.
bmp280test.ino:20:29: fatal error: Adafruit_Sensor.h: No such file or directory

Is it expected to work on that platform at all? 
Thanks

**Comment by ladyada** [comment]
no, this is totally the wrong code to use - its for arduino only!

**Comment by mikelupo** [comment]
Aside from writing one of my own, is there any hope of getting a library for other platforms?
