### ISSUE TITLE
BMP 280 for both 0x76 and 0x77 Addresses

### ISSUE THREAD

**Issue by sellensr** [adafruit/Adafruit_BMP280_Library#41]
Recently ran into some breakouts with default address of 0x76 for BMP 280.

The code needs the same fixes as were applied in https://github.com/adafruit/Adafruit_BME280_Library/pull/49

**Comment by ladyada** [comment]
hi
that PR was not a good idea, it caused problems and was reverted

https://github.com/adafruit/Adafruit_BMP280_Library/blob/master/Adafruit_BMP280.h#L190
