### ISSUE TITLE
error: 'class Adafruit_BMP280' has no member named 'setI2CAddress' and further errors ...

### ISSUE THREAD

**Issue by AstroMob** [adafruit/Adafruit_BMP280_Library#46]
Dear all,

I''d like to use this ship for model rocketry but I get those errors during compiling:

C:\Travail\Perso\Arduino\Fusées\Ordi Vol\OrdiVol-V1\OrdiVol-V1.ino: In function 'bool initbmp()':
C:\Travail\Perso\Arduino\Fusées\Ordi Vol\OrdiVol-V1\OrdiVol-V1.ino:176:7: error: 'class Adafruit_BMP280' has no member named 'setI2CAddress'
C:\Travail\Perso\Arduino\Fusées\Ordi Vol\OrdiVol-V1\OrdiVol-V1.ino:177:7: error: 'class Adafruit_BMP280' has no member named 'setPressureOverSample'
C:\Travail\Perso\Arduino\Fusées\Ordi Vol\OrdiVol-V1\OrdiVol-V1.ino:178:7: error: 'class Adafruit_BMP280' has no member named 'beginI2C'
C:\Travail\Perso\Arduino\Fusées\Ordi Vol\OrdiVol-V1\OrdiVol-V1.ino: In function 'void getBMP()':
C:\Travail\Perso\Arduino\Fusées\Ordi Vol\OrdiVol-V1\OrdiVol-V1.ino:184:18: error: 'class Adafruit_BMP280' has no member named 'readFloatPressure'
C:\Travail\Perso\Arduino\Fusées\Ordi Vol\OrdiVol-V1\OrdiVol-V1.ino:185:18: error: 'class Adafruit_BMP280' has no member named 'readFloatAltitudeMeters'
C:\Travail\Perso\Arduino\Fusées\Ordi Vol\OrdiVol-V1\OrdiVol-V1.ino: In function 'bool initmpu()':
C:\Travail\Perso\Arduino\Fusées\Ordi Vol\OrdiVol-V1\OrdiVol-V1.ino:196:1: warning: control reaches end of non-void function [-Wreturn-type]
Erreur de compilation pour la carte Teensy 4.1

- Arduino IDE version 1.18.13
- Board Teensy 4.1

Thank's in advance.

AstroMob

**Comment by ladyada** [comment]
you're using the wrong library - ask the author for advice. we do not have `setI2CAddress`
