### ISSUE TITLE
Mode forced not working

### ISSUE THREAD

**Issue by BimoSora** [adafruit/Adafruit_BMP280_Library#62]
I tried this code and when it appeared on the screen it didn't want to change it even though in normal mode it could run and change, what's wrong with this code?
```
bme.setSampling(Adafruit_BME280::MODE_FORCED,
                 Adafruit_BMP280::SAMPLING_X1, /* Temp. oversampling */
                 Adafruit_BMP280::SAMPLING_X1,/* Pressure oversampling */
                 Adafruit_BMP280::FILTER_OFF);  /* Filtering. */
```

**Comment by BimoSora** [comment]
OK, it worked and worked perfectly and I just removed the // and /* flags in .cpp and .h. Why is there no ms 60000 in the library?

**Comment by caternuson** [comment]
The available BMP280 standby times are, from the datasheet:
![image](https://user-images.githubusercontent.com/8755041/137759632-6ecedc74-8765-42b1-a61e-117d71c41dc7.png)

There is no 60000ms option.

**Comment by caternuson** [comment]
In forced mode, that timing is up to your user code to handle. Note how it's not shown as being a `t_standby` option:
![image](https://user-images.githubusercontent.com/8755041/137772531-303ce3aa-e5de-4e32-9216-5ac2f27af9f7.png)
