### ISSUE TITLE
Spelling mistake readTemperature method

### ISSUE THREAD

**Issue by matthboers** [adafruit/Adafruit_BMP280_Library#71]
Slight nitpick...
**Line 246** of `Adafruit_BMP280.cpp`

` * @return The temperature in degress celcius.`
 Should be
` * @return The temperature in degrees celsius.`

**Comment by dhalbert** [comment]
A pull request to fix this (and any other typos) is welcome.

**Comment by caternuson** [comment]
Fixed with #74
