### ISSUE TITLE
not found in library: printSensorDetails

### ISSUE THREAD

**Issue by mahesh2000** [adafruit/Adafruit_BMP280_Library#73]
not found in library: printSensorDetails

https://github.com/adafruit/Adafruit_BMP280_Library/blob/8b26e5f6a1f83c0faf8c4a54412f8b2bf7d7bb05/examples/bmp280_sensortest/bmp280_sensortest.ino#L53

**Comment by caternuson** [comment]
It's from the base class, which is in another library:
https://github.com/adafruit/Adafruit_Sensor/blob/69d2d4f128458c7f7e6d56b583a8261ea234971b/Adafruit_Sensor.h#L182
